In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6])

In [7]:
type(arr)

numpy.ndarray

In [9]:
arr1 = np.arange(2,25,2)

In [11]:
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [29]:
arr2 = np.linspace(2,15,14)

In [31]:
arr2

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15.])

In [17]:
 2.89655172 - 2.44827586

0.4482758600000003

In [19]:
2.44827586 - 2.00000000

0.44827585999999986

In [33]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [35]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
np.full(5,7)

array([7, 7, 7, 7, 7])

In [39]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [41]:
np.random.randint(1,15,(3,4))

array([[ 4,  6,  6,  7],
       [12,  3,  3, 13],
       [ 4,  1, 10,  1]])

In [43]:
arr

array([1, 2, 3, 4, 5, 6])

In [45]:
arr + 2

array([3, 4, 5, 6, 7, 8])

In [47]:
np.sum(arr)

21

In [49]:
np.min(arr)

1

In [51]:
np.max(arr)

6

In [53]:
max(arr)

6

In [55]:
np.mean(arr)

3.5

In [57]:
np.std(arr)

1.707825127659933

In [61]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [63]:
np.sin(90)

0.8939966636005579

In [67]:
pi = 180

In [69]:
np.sin(pi/2)

0.8939966636005579

In [71]:
np.pi

3.141592653589793

In [73]:
arr[arr > 2]

array([3, 4, 5, 6])

In [79]:
np.reshape(arr,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
list1 = [i for i in range(1,1000000)]
list2 = [i for i in range(1,1000000)]

arr1 = np.array(list1)
arr2 = np.array(list2)

In [9]:
import sys

In [15]:
sys.getsizeof(list())

56

In [19]:
sys.getsizeof(np.array([]))

112

In [25]:
sys.getsizeof([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

184

In [27]:
sys.getsizeof(np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]))

172

In [29]:
sys.getsizeof(list1)

8448728

In [31]:
sys.getsizeof(arr1)

4000108

In [6]:
import time

In [40]:
list3 = [i for i in range(1,1000000)]
start = time.time()
for i in range(len(list1)):
    list3[i] = list1[i] + list2[i]
end = time.time()
total = end - start

In [42]:
total

0.35765886306762695

In [8]:
start = time.time()
arr3 = arr1 + arr2
end = time.time()
total = end - start
total

0.0019783973693847656